import { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiArrowUpRight,
  HiOutlineArrowPath,
  HiCheck,
  HiMiniQuestionMarkCircle,
  HiMiniXMark,
  HiOutlineLink,
  HiExclamationTriangle,
  HiInformationCircle,
  HiExclamationCircle,
  HiCheckCircle,
  HiMiniGlobeAsiaAustralia,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiClipboard,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiBriefcaseDuotone,
  PiSparkleDuotone,
  PiTrophyDuotone,
  PiSunDuotone,
  PiMoonDuotone,
  PiRocketLaunchDuotone,
  PiGaugeDuotone,
  PiShoppingCartDuotone,
  PiChartLineUpDuotone,
  PiUsersThreeDuotone,
  PiLightbulbDuotone,
  PiRobotDuotone,
  PiGraduationCapDuotone,
  PiLockSimpleDuotone,
  PiClockDuotone,
  PiPlayCircleDuotone,
} from "react-icons/pi";

import { FaDiscord, FaGithub, FaLinkedin, FaXTwitter, FaYoutube } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  arrowUpRight: HiArrowUpRight,
  check: HiCheck,
  arrowRight: HiArrowRight,
  helpCircle: HiMiniQuestionMarkCircle,
  infoCircle: HiInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  email: HiEnvelope,
  globe: HiMiniGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  youtube: FaYoutube,
  linkedin: FaLinkedin,
  x: FaXTwitter,
  clipboard: HiClipboard,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  briefcase: PiBriefcaseDuotone,
  sparkle: PiSparkleDuotone,
  trophy: PiTrophyDuotone,
  sun: PiSunDuotone,
  moon: PiMoonDuotone,
  rocket: PiRocketLaunchDuotone,
  gauge: PiGaugeDuotone,
  cart: PiShoppingCartDuotone,
  chartUp: PiChartLineUpDuotone,
  team: PiUsersThreeDuotone,
  lightbulb: PiLightbulbDuotone,
  robot: PiRobotDuotone,
  graduationCap: PiGraduationCapDuotone,
  lock: PiLockSimpleDuotone,
  clock: PiClockDuotone,
  playCircle: PiPlayCircleDuotone,
};
